-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-11-04 11:09:34 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE baju_man (
    id_baju_man INTEGER NOT NULL,
    nama        VARCHAR(100) NOT NULL,
    harga       INTEGER NOT NULL,
    gambar      VARCHAR(255) NOT NULL,
    link        VARCHAR(255) NOT NULL
);

ALTER TABLE baju_man ADD CONSTRAINT baju_man_pk PRIMARY KEY ( id_baju_man );

CREATE TABLE baju_woman (
    id_baju_woman INTEGER NOT NULL,
    nama          VARCHAR(100) NOT NULL,
    harga         INTEGER NOT NULL,
    gambar        VARCHAR(255) NOT NULL,
    link          VARCHAR(255) NOT NULL
);

ALTER TABLE baju_woman ADD CONSTRAINT baju_woman_pk PRIMARY KEY ( id_baju_woman );

CREATE TABLE celana_man (
    id_celana_man INTEGER NOT NULL,
    nama          VARCHAR(100) NOT NULL,
    harga         INTEGER NOT NULL,
    gambar        VARCHAR(255) NOT NULL,
    link          VARCHAR(255) NOT NULL
);

ALTER TABLE celana_man ADD CONSTRAINT celana_man_pk PRIMARY KEY ( id_celana_man );

CREATE TABLE celana_woman (
    id_celana_woman INTEGER NOT NULL,
    nama            VARCHAR(100) NOT NULL,
    harga           INTEGER NOT NULL,
    gambar          VARCHAR(255) NOT NULL,
    link            VARCHAR(255) NOT NULL
);

ALTER TABLE celana_woman ADD CONSTRAINT celana_woman_pk PRIMARY KEY ( id_celana_woman );

CREATE TABLE kategori (
    id_kategori                    INTEGER NOT NULL,
    pakaian_woman_id_pakaian_woman VARCHAR(255) NOT NULL,
    pakaian_man_id_pakaian_man     VARCHAR(255) NOT NULL,
    user_id_user                   INTEGER NOT NULL
);

ALTER TABLE kategori ADD CONSTRAINT kategori_pk PRIMARY KEY ( id_kategori );

CREATE TABLE pakaian_man (
    id_pakaian_man           VARCHAR(255) NOT NULL,
    baju_man_id_baju_man     INTEGER NOT NULL,
    celana_man_id_celana_man INTEGER NOT NULL,
    sepatu_man_id_sepatu     INTEGER NOT NULL
);

ALTER TABLE pakaian_man ADD CONSTRAINT pakaian_man_pk PRIMARY KEY ( id_pakaian_man );

CREATE TABLE pakaian_woman (
    id_pakaian_woman             VARCHAR(255) NOT NULL,
    baju_woman_id_baju_woman     INTEGER NOT NULL,
    celana_woman_id_celana_woman INTEGER NOT NULL,
    sepatu_woman_id_sepatu_woman INTEGER NOT NULL
);

ALTER TABLE pakaian_woman ADD CONSTRAINT pakaian_woman_pk PRIMARY KEY ( id_pakaian_woman );

CREATE TABLE sepatu_man (
    id_sepatu INTEGER NOT NULL,
    nama      VARCHAR(100) NOT NULL,
    harga     INTEGER NOT NULL,
    gambar    VARCHAR(255) NOT NULL,
    link      VARCHAR(255) NOT NULL
);

ALTER TABLE sepatu_man ADD CONSTRAINT sepatu_man_pk PRIMARY KEY ( id_sepatu );

CREATE TABLE sepatu_woman (
    id_sepatu_woman INTEGER NOT NULL,
    nama            VARCHAR(100) NOT NULL,
    harga           INTEGER NOT NULL,
    gambar          VARCHAR(255) NOT NULL,
    link            VARCHAR(255) NOT NULL
);

ALTER TABLE sepatu_woman ADD CONSTRAINT sepatu_woman_pk PRIMARY KEY ( id_sepatu_woman );

CREATE TABLE USER (
    id_user  INTEGER NOT NULL,
    nama     VARCHAR(30) NOT NULL,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(60) NOT NULL,
    gender   CHAR(1) NOT NULL
);

ALTER TABLE USER ADD CONSTRAINT user_pk PRIMARY KEY ( id_user );

ALTER TABLE kategori
    ADD CONSTRAINT kategori_pakaian_man_fk FOREIGN KEY ( pakaian_man_id_pakaian_man )
        REFERENCES pakaian_man ( id_pakaian_man );

ALTER TABLE kategori
    ADD CONSTRAINT kategori_pakaian_woman_fk FOREIGN KEY ( pakaian_woman_id_pakaian_woman )
        REFERENCES pakaian_woman ( id_pakaian_woman );

ALTER TABLE kategori
    ADD CONSTRAINT kategori_user_fk FOREIGN KEY ( user_id_user )
        REFERENCES USER ( id_user );

ALTER TABLE pakaian_man
    ADD CONSTRAINT pakaian_man_baju_man_fk FOREIGN KEY ( baju_man_id_baju_man )
        REFERENCES baju_man ( id_baju_man );

ALTER TABLE pakaian_man
    ADD CONSTRAINT pakaian_man_celana_man_fk FOREIGN KEY ( celana_man_id_celana_man )
        REFERENCES celana_man ( id_celana_man );

ALTER TABLE pakaian_man
    ADD CONSTRAINT pakaian_man_sepatu_man_fk FOREIGN KEY ( sepatu_man_id_sepatu )
        REFERENCES sepatu_man ( id_sepatu );

ALTER TABLE pakaian_woman
    ADD CONSTRAINT pakaian_woman_baju_woman_fk FOREIGN KEY ( baju_woman_id_baju_woman )
        REFERENCES baju_woman ( id_baju_woman );

ALTER TABLE pakaian_woman
    ADD CONSTRAINT pakaian_woman_celana_woman_fk FOREIGN KEY ( celana_woman_id_celana_woman )
        REFERENCES celana_woman ( id_celana_woman );

ALTER TABLE pakaian_woman
    ADD CONSTRAINT pakaian_woman_sepatu_woman_fk FOREIGN KEY ( sepatu_woman_id_sepatu_woman )
        REFERENCES sepatu_woman ( id_sepatu_woman );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
INSERT INTO `baju_man` (`id_baju_man`, `nama`, `harga`, `gambar`, `link`) VALUES
	(1, 'Polo shirt Kaos Kerah lengan panjang Ua Golf', 150000, 'bm_1', 'https://tokopedia.link/TUDYQoAU4kb'),
	(2, 'KAOS POLO / KERAH / GOLF PRIA CUTI LAKOS ORIGINAL PIER ONE RETAIL 700K - S, Putih', 99000, 'bm_2', 'https://tokopedia.link/q9rYZawU4kb'),
	(3, 'Kaos Someone Gold Koi 172D Glow In The Dark - S', 75000, 'bm_3', 'https://tokopedia.link/zbescSEU4kb'),
	(4, 'Kith X MLB New York Yankees NY Embroidery T-Shirt Navy - M', 189070, 'bm_4', 'https://tokopedia.link/qA9i3NMU4kb'),
	(5, 'Human Made 2026 T-Shirt Black - M', 179280, 'bm_5', 'https://tokopedia.link/37BWfqPU4kb');

INSERT INTO `celana_man` (`id_celana_man`, `nama`, `harga`, `gambar`, `link`) VALUES
	(1, 'Motz Chino Washing Basic Reguler Cream - XL', 492750, 'cm_1', 'https://tokopedia.link/pDHh8I6U4kb'),
	(2, 'https://tokopedia.link/CKfE9D2U4kb', 179280, 'cm_2', 'https://tokopedia.link/CKfE9D2U4kb'),
	(3, 'UNQ Slim Fit Chino Pants Olive - 33/85', 179, 'cm_3', 'https://tokopedia.link/tb2bi80U4kb');

INSERT INTO `sepatu_man` (`id_sepatu`, `nama`, `harga`, `gambar`, `link`) VALUES
	(1, 'BRODO - Sneakers Pria Active Zeal Beast Olive Orange IS - 41', 530, 'sm_1', 'https://tokopedia.link/8lmpaTtV4kb'),
	(2, 'Sneakers Pria BRODO Base Lite All White GS - 41', 299000, 'sm_2', 'https://tokopedia.link/5HtOl8rV4kb');

INSERT INTO `user` (`id_user`, `nama`, `username`, `password`, `gender`) VALUES
	(69, 'Jhhonathan', 'jhonny', 'jhonny123', 'l');

